# Generated by Django 3.1.7 on 2021-05-17 22:35

import apps.product.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product category',
            },
        ),
        migrations.CreateModel(
            name='ProductCommandForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Name')),
                ('field_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('initial_values', models.CharField(blank=True, help_text='Put here the choices separated by a comma', max_length=50, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('choices', 'Choix'), ('int', 'Integer'), ('archived', 'Archived - not available anymore')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Product form field',
                'verbose_name_plural': 'Product form fields',
            },
        ),
        migrations.CreateModel(
            name='TypeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.ManyToManyField(to='product.ProductCommandForm')),
            ],
            options={
                'verbose_name': 'Product form type',
                'verbose_name_plural': 'Product form type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('identifier', models.CharField(blank=True, default='8255383486', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Product price', max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.product.models.product_image_directory_path)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('type_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.typeform')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
