# Generated by Django 3.1.7 on 2021-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210219_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommandForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('initial_values', models.CharField(blank=True, help_text='Put here the choices separated by a comma', max_length=50, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('choices', 'Choix'), ('int', 'Integer'), ('archived', 'Archived - not available anymore')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.ManyToManyField(to='product.ProductCommandForm'),
        ),
    ]
