# Generated by Django 3.1.7 on 2021-04-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210403_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
