# Generated by Django 3.1.7 on 2021-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcommandform',
            options={'verbose_name': 'Product form field', 'verbose_name_plural': 'Product form fields'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='form',
        ),
        migrations.CreateModel(
            name='TypeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.ManyToManyField(to='product.ProductCommandForm')),
            ],
            options={
                'verbose_name': 'Product form type',
                'verbose_name_plural': 'Product form type',
            },
        ),
    ]
