# Generated by Django 3.1.7 on 2021-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210405_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.typeform'),
        ),
    ]
