# Generated by Django 3.1.7 on 2021-05-17 22:36

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20210517_2236'),
        ('customer', '0004_auto_20210517_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, default='6171962770', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('EN_COURS', 'En cours de validation'), ('EN_COURS_DE_TRAITEMENT', 'En cours de traitement'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Commande livrée'), ('RETOUR_MAGASIN', 'Retour en magasin'), ('ANNULEE', 'Commande annulée')], max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
            },
        ),
    ]
