# Generated by Django 3.1.7 on 2021-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='identifier',
            field=models.CharField(blank=True, default='4732955406', max_length=50, null=True),
        ),
    ]
