# Generated by Django 3.1.7 on 2021-05-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210522_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, help_text='Product price'),
        ),
        migrations.AlterField(
            model_name='command',
            name='identifier',
            field=models.CharField(blank=True, default='3220997572', max_length=50, null=True),
        ),
    ]
