# Generated by Django 3.1.7 on 2021-05-22 23:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210522_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='command',
            name='identifier',
            field=models.CharField(blank=True, default='3760726296', max_length=50, null=True),
        ),
    ]
