# Generated by Django 3.1.7 on 2021-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_authorizedoverdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedoverdraft',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='authorizedoverdraft',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizedoverdraft',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
