# Generated by Django 3.1.7 on 2021-04-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210402_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='identifier',
        ),
    ]
