# Generated by Django 3.1.7 on 2021-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identifier',
            field=models.CharField(blank=True, default='3818075948', max_length=50, null=True),
        ),
    ]
