# Generated by Django 3.1.7 on 2021-04-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210402_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofs',
            name='content',
        ),
        migrations.AlterField(
            model_name='customer',
            name='identifier',
            field=models.CharField(blank=True, default='1438594618', max_length=50, null=True),
        ),
    ]
