# Generated by Django 3.1.7 on 2021-04-05 21:00

import apps.customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20210405_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofs',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=apps.customer.models.proof_directory_path),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identifier',
            field=models.CharField(blank=True, default='5099624872', max_length=50, null=True),
        ),
    ]
