# Generated by Django 3.1.7 on 2021-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210405_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofs',
            name='content',
        ),
        migrations.AlterField(
            model_name='customer',
            name='identifier',
            field=models.CharField(blank=True, default='2810862729', max_length=50, null=True),
        ),
    ]
